# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZEGOLiveDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZEGOLiveDemo
  pod 'ZIM','1.3.7'
  pod 'ZegoExpressEngine'
  
end
